### ISSUE TITLE
Whole thing not work properly

### ISSUE THREAD

**Issue by amiraligull** [JustalK/ANIME-API#15]
have a lot of errors and I tried everything which you  provide in the documentation but all wast nothing working Thanks for your hard work

**Comment by JustalK** [comment]
Hello @amiraligull,

I am working on a new concept to make this project work.

Most of the website are using cloudflare to protect from crawler such as this api.
I manage to pass over it. However, one big problem remains. 
The links pointing to the images and animes are updated randomly after a period of time. I have not found a way to pass over that without doing it manually.

I am really busy with my jobs and my kids, so I cannot keep up with those update.
If you have an idea, it's welcome but for the moment I am banging my head against a wall.

**Comment by amiraligull** [comment]
Hello @JustalK 
first of all thanks for the instant reply, it's okay you already did a great job hope we will find the solution soon.
